#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Ritwik G

# Short bio or description (displayed in the header)
description: Coding Geek

author:
  name: Ritwik G
  picture: "/assets/profile.jpg"
  email: i@ritwikg.com
  twitter:
  links:
    - title: linkedin
      url: https://www.linkedin.com/in/ritwik-g/
      icon: fab fa-linkedin
    - title: GitHub
      url: https://github.com/RitwikGopi
      icon: fab fa-github-square
    - title: Instagram
      url: https://www.instagram.com/ritwikgopi/
      icon: fab fa-instagram

# Footer Links
footer_links:
  - title: linkedin
    url: https://www.linkedin.com/in/ritwik-g/
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/RitwikGopi
    icon: fab fa-github-square
  - title: Instagram
    url: https://www.instagram.com/ritwikgopi/
    icon: fab fa-instagram

tag_archive_path: "/tags/#"
categories_archive_path: "/tags/#"

defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "/assets/cover.png"
logo: "/assets/cover.png"
skin: "/assets/css/skins/dark.css"
read_time: true
words_per_minute: 200

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: ritwikgopi@gmail.com
  facebook:
  flickr:
  github: RitwikGopi
  instagram:
  linkedin: https://www.linkedin.com/in/ritwik-g/
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:
  shortname: include-1

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-JH7XP5ZG39

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://blog.ritwikg.com/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:categories/:title/

# # Taxonomy pages
category_archive_path: "/categories/"
# tag_archive_path: "/tags/"

# Collections
collections:
  category:
    output: false
    permalink: /categories/:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

remote_theme: "mmistakes/so-simple-theme@3.2.0"